name: Docker Image CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image and push
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: uganad/kakelvers
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
