name: Docker Image CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v4
      - name: Build push docker image
        with: 
          image: uganad/kakelvers
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrests.DOCKER_PASSWORD}}
