name: Docker Image CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
        run:|
          echo "${{ secrets.dockerPW }}" | docker login -u "uganad" --password-stdin "GFYsUxMTkKQgT3K"
          docker image build -t uganad/frontend-app-react .
          docker push docker push uganad/kakelvers
