name: Docker Image CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build push docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "uganad" --password-stdin
          docker image build -t owlberd/frontend-kakelvers-webpack5 .
          docker tag bb38976d03cf uganad/frontend-kakelvers-webpack5:firsttry
          docker push uganad/kakelvers:latest
